### PR TITLE
Fix _IACTG_TFM property for .NET Core

### PR DESCRIPTION
**Pull request by 0xced**
The target framework was upgraded from netstandard1.3 to netstandard2.0 in #8 in the project file but was not updated in the targets file.

### CODE REVIEW

**Comment by aelij** [comment]
Thanks for the fix :)

**Comment by 0xced** [comment]
Thanks for merging. Do you plan to release a new version on NuGet any time soon?

**Comment by aelij** [comment]
I've published it now.

**Comment by 0xced** [comment]
Awesome, thanks! 🎉

**Pull request merged**
