### PR TITLE
The excludedTypeNames local should not be initialized from the Assemb…

### PR DESCRIPTION
**Pull request by RobertvanderHulst**
…lyNames property but from the ExcludeTypeNames property

### CODE REVIEW

**Comment by aelij** [comment]
Thanks for the fix!

**Comment by BlueAmulet** [comment]
Can we get this pushed to nuget? The version on nuget doesn't contain this fix and you have to specify excludes with additional InternalsAssemblyName statements.

**Comment by RobertvanderHulst** [comment]
I am sorry, but I gave up using this. The code that I am working with uses too many assemblies with ik internal types. it was too hard to handle them all.

**Comment by BlueAmulet** [comment]
You already did you part by fixing the bug, but the fix has been sitting in the repository for months now and no new version has been published to nuget with the fix. That's why I'm asking aelij

**Comment by RobertvanderHulst** [comment]
I am sorry, but I gave up using this. The code that I am working with uses too many assemblies with ik internal types. it was too hard to handle them all.

I will look at my code next week and push it and send a pull request.

**Comment by BlueAmulet** [comment]
??? You literally don't have to do anything. This was the pull request, it was already merged in, the code works, it's just not on nuget...

**Comment by RobertvanderHulst** [comment]
Publishing on nuget must be done by the owner.

**Pull request merged**
